menu:
  Home:
  Archivos: archives

widgets:
- search
- category
- tag

excerpt_link: Read More

twitter:
  username: joelerll95
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: false
  pinterest: false

fancybox: false

google_analytics:
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid: 247425462386888
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
